// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace MAVN.Service.NotificationSystemAudit.MsSqlRepositories.Migrations
{
    [DbContext(typeof(AuditMessageContext))]
    [Migration("20190611091946_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auditmessage")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MAVN.Service.NotificationSystemAudit.MsSqlRepositories.Entities.AuditMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CallType")
                        .HasMaxLength(20);

                    b.Property<DateTime>("CreationTimestamp");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("DeliveryComment")
                        .HasMaxLength(10000);

                    b.Property<int>("DeliveryStatus")
                        .HasMaxLength(40);

                    b.Property<string>("FormattingComment")
                        .HasMaxLength(10000);

                    b.Property<int>("FormattingStatus")
                        .HasMaxLength(40);

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("MessageTemplateId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<DateTime>("SentTimestamp");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("SubjectTemplateId")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryStatus");

                    b.HasIndex("MessageType");

                    b.HasIndex("SentTimestamp");

                    b.HasIndex("Source");

                    b.ToTable("AuditMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
